services:
  bot-service:
    build:
      context: ./
      dockerfile: ./bot_service/Dockerfile
    restart: unless-stopped

  collector-service:
    build:
       context: ./
       dockerfile: ./collector_service/Dockerfile
    restart: unless-stopped